all: summation summation4 summation5

summation: summation.c
	gcc -o sum summation -lm -lpthread
summation4: summation4.c
	gcc -o sum4 summation4 -lm -lpthread
summation5: summation5.c
	gcc -o sum5 summation5 -lm -lpthread
