all:	dp problem1 problem2 problem3-1 problem3-2

dp:	dp.c
	gcc -std=c99 -g  -o dp dp.c -lpthread

problem1: problem1.c
	gcc -std=c99 -g -o problem1 problem1.c -lpthread

problem2: problem2.c
	gcc -std=c99 -g -o problem2 problem2.c -lpthread
problem3-1: problem3-1.c
	gcc -std=c99 -g -o problem3-1 problem3-1.c -lpthread
problem3-2: problem3-2.c
	gcc -std=c99 -g -o problem3-2 problem3-2.c -lpthread
clean:
	/bin/rm *~